[workspace]
members = ["dvs", "dvs-cli"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1

[workspace.package]
version = "0.3.0"
authors = [
    'Jenna Johnson <jenna@a2-ai.com>',
    'Devin Pastoor <devin@a2-ai.com>',
    'Mossa Merhi Reimert <mossa@a2-ai.com>',
    'A2-Ai',
]
description = 'This package allows users to version large or sensitive files under Git without tracking the file directly.'
license = 'MIT'
edition = '2024'
rust-version = '1.85'

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.9"
fs-err = "3"
log = "0.4.29"
blake3 = "1.8.3"
walkdir = "2"
md5 = "0.8.0"
jiff = { version = "0.2.18", features = ["serde"] }
anyhow = "1.0.100"
whoami = "2"
uuid = { version = "1.20.0", features = ["v4"] }
zstd = "0.13.3"
rusqlite = { version = "0.38", features = ["bundled"] }
globset = "0.4"
rayon = "1.10"

[profile.dev-cli]
inherits = "release"
debug-assertions = true
