[package]
name = "dvs-rpkg"
version = "0.3.0"
edition = "2024"
rust-version = '1.85'
publish = false

# Make this a standalone workspace (prevents inheriting from parent)
[workspace]

[lib]
name = "dvs"
path = "lib.rs"
crate-type = ["staticlib"]

[features]
default = []
nonapi = ["miniextendr-api/nonapi"]
connections = ["miniextendr-api/connections"]

[dependencies]
miniextendr-api = { version = "*", features = ["serde"] }
dvs = { version = "*", path = "../../vendor/dvs" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"

[build-dependencies]
miniextendr-lint = { version = "*" }

[profile.dev]
codegen-units = 1

[profile.release]
codegen-units = 1

[patch]

[patch.crates-io]
dvs = { path = "../../vendor/dvs" }
miniextendr-macros-core = { path = "../../vendor/miniextendr-macros-core" }
miniextendr-lint = { path = "../../vendor/miniextendr-lint" }
miniextendr-api = { path = "../../vendor/miniextendr-api" }
miniextendr-macros = { path = "../../vendor/miniextendr-macros" }
