# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: run `devtools::document()` or rebuild the package.
# nolint start
# nocov start

# Generated from Rust fn `dvs_init` (lib.rs:28:8)
#' @title Initialize a new DVS repository
#' @param directory Path to the storage directory.
#' @param group Optional Unix group for storage files.
#' @param metadata_folder_name Optional custom metadata folder name (default `.dvs`).
#' @return A list with `status = "initialized"`.
#' @export
#' @source Generated by miniextendr from Rust fn `dvs_init`
dvs_init <- function(directory = ".", group = NULL, metadata_folder_name = NULL) {
  .Call(C_dvs_init, .call = match.call(), directory, group, metadata_folder_name)
}

# Generated from Rust fn `dvs_add` (lib.rs:53:8)
#' @title Add files to DVS storage
#' @param files Character vector of file paths to add.
#' @param message Optional commit message.
#' @param verbose Verbosity level. `FALSE`/`0` = quiet, `TRUE`/`1` = progress,
#' `2` = per-step detail, `3` = detail + CSV timing log written to working directory.
#' @return A data.frame with columns `path`, `outcome`, `hash`, `size` (or `error`).
#' @export
#' @source Generated by miniextendr from Rust fn `dvs_add`
dvs_add <- function(files, message = quote(expr=), verbose = 0L) {
  .Call(C_dvs_add, .call = match.call(), files, message, verbose)
}

# Generated from Rust fn `dvs_status` (lib.rs:87:8)
#' @title Get the status of all tracked files
#' @param verbose Verbosity level. `FALSE`/`0` = quiet, `TRUE`/`1` = progress,
#' `2` = per-step detail, `3` = detail + CSV timing log written to working directory.
#' @return A data.frame with columns `path` and `status` (or `error`).
#' @export
#' @source Generated by miniextendr from Rust fn `dvs_status`
dvs_status <- function(verbose = 0L) {
  .Call(C_dvs_status, .call = match.call(), verbose)
}

# Generated from Rust fn `dvs_get` (lib.rs:108:8)
#' @title Retrieve files from DVS storage
#' @param files Character vector of file paths to retrieve.
#' @param verbose Verbosity level. `FALSE`/`0` = quiet, `TRUE`/`1` = progress,
#' `2` = per-step detail, `3` = detail + CSV timing log written to working directory.
#' @return A data.frame with columns `path`, `outcome`, `size` (or `error`).
#' @export
#' @source Generated by miniextendr from Rust fn `dvs_get`
dvs_get <- function(files, verbose = 0L) {
  .Call(C_dvs_get, .call = match.call(), files, verbose)
}

# nocov end
# nolint end
