# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: rebuild the package (R CMD INSTALL or devtools::install).
# nolint start
# nocov start

# Internal helper: re-raise a tagged Rust error/condition value as an R condition.
# Generated wrappers call this whenever `.Call()` returns a `rust_condition_value`.
# `.call_default` is the wrapper's `sys.call()`, used as the fallback when the
# Rust panic payload didn't carry a captured call (e.g. lambda contexts that
# pass `.call = NULL` to `.Call`). For error/panic kinds `stop()` longjmps;
# for warning/message/condition the helper signals and returns invisible(NULL),
# which the wrapper's surrounding `return(...)` propagates as its result.
.miniextendr_raise_condition <- function(.val, .call_default) {
  .msg <- .val$error
  .call <- (if (is.null(.val$call)) .call_default else .val$call)
  .class <- .val$class
  # `.val$data` is an optional named list of structured fields (from the
  # macros' `data = ...` form). When present, splice its named elements into
  # the condition object alongside message/call/kind so handlers can read
  # `e$<name>`. `utils::modifyList` keeps the base fields and appends the
  # data fields; a malformed (non-list / unnamed) payload is ignored.
  .data <- .val$data
  .cond_fields <- function(base) {
    if (is.null(.data) || !is.list(.data) || is.null(names(.data))) {
      base
    } else {
      utils::modifyList(base, .data)
    }
  }
  switch(.val$kind,
    error = stop(structure(.cond_fields(list(message = .msg, call = .call, kind = "error")),
      class = c(.class, "rust_error", "simpleError", "error", "condition"))),
    warning = warning(structure(.cond_fields(list(message = .msg, call = .call, kind = "warning")),
      class = c(.class, "rust_warning", "simpleWarning", "warning", "condition"))),
    message = message(structure(.cond_fields(list(message = paste0(.msg, "\n"), call = NULL, kind = "message")),
      class = c(.class, "rust_message", "simpleMessage", "message", "condition"))),
    condition = signalCondition(structure(.cond_fields(list(message = .msg, call = .call, kind = "condition")),
      class = c(.class, "rust_condition", "simpleCondition", "condition"))),
    panic = stop(structure(list(message = .msg, call = .call, kind = "panic"),
      class = c("rust_error", "simpleError", "error", "condition"))),
    stop(structure(list(message = .msg, call = .call, kind = .val$kind),
      class = c("rust_error", "simpleError", "error", "condition")))
  )
  invisible(NULL)
}

# Generated from Rust impl `ProgressBarCallback` (lib.rs:113:6)
#' @title ProgressBarCallback  Class
#' @name ProgressBarCallback
#' @rdname ProgressBarCallback
#' @source Generated by miniextendr from Rust type `ProgressBarCallback`
#' @keywords internal
ProgressBarCallback <- new.env(parent = emptyenv())

# ProgressBarCallback::new (115:12)
#' @title Create a progress callback handle (signals that progress should be shown)
#' @name ProgressBarCallback$new
#' @rdname ProgressBarCallback
#' @source Generated by miniextendr from `ProgressBarCallback::new`
ProgressBarCallback$new <- function() {
  .val <- .Call(C_ProgressBarCallback__new, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  self <- .val
  class(self) <- "ProgressBarCallback"
  self
}

#' @export
`$.ProgressBarCallback` <- function(self, name) {
  obj <- ProgressBarCallback[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(ProgressBarCallback)) {
      ns <- ProgressBarCallback[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @export
`[[.ProgressBarCallback` <- `$.ProgressBarCallback`

# Generated from Rust fn `dvs_test_2_5_gib_bytes` (test_support.rs:6:8)
#' @title test support
#' @rdname test_support
#' @source Generated by miniextendr from Rust fn `dvs_test_2_5_gib_bytes`
dvs_test_2_5_gib_bytes <- function() {
  .val <- .Call(C_dvs_test_2_5_gib_bytes, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `dvs_add` (lib.rs:195:15)
#' @title Add files to DVS-managed storage
#' @description Hashes and copies the specified files into DVS storage.
#' @param paths Character vector of file paths to add to DVS storage.
#' @param message Optional commit message describing why the files were added.
#' @param glob Optional glob pattern to select files (e.g. `"data/*.csv"`).
#' Globs use a literal path separator: `*.csv` only matches files in the
#' target directory and will not match `subdir/file.csv`. Use `**/*.csv` to
#' match recursively across subdirectories.
#' @param dry_run If `TRUE`, report what would be added without modifying anything.
#' @param progress_callback Optional handle to enable progress bar display.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_add`
dvs_add_impl <- function(paths = character(0), message = NULL, glob = NULL, dry_run = NULL, progress_callback = NULL) {
  stopifnot(
    "'message' must be NULL or character" = is.null(message) || is.character(message),
    "'message' must be NULL or have length 1" = is.null(message) || length(message) == 1L,
    "'glob' must be NULL or character" = is.null(glob) || is.character(glob),
    "'glob' must be NULL or have length 1" = is.null(glob) || length(glob) == 1L,
    "'dry_run' must be NULL or logical" = is.null(dry_run) || is.logical(dry_run),
    "'dry_run' must be NULL or have length 1" = is.null(dry_run) || length(dry_run) == 1L
  )
  .val <- .Call(C_dvs_add, .call = match.call(), paths, message, glob, dry_run, progress_callback)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `dvs_get` (lib.rs:442:15)
#' @title Retrieve files from DVS storage into the working directory
#' @description Fetches the specified files from DVS storage and writes them to their original paths in the working directory. With no `paths` or `glob`, `dvs_get()` scopes to the working directory: it restores the files directly under it, and `dvs_get(recursive = TRUE)` restores every tracked file beneath it at any depth.
#' @param paths Character vector of file paths to retrieve from DVS storage.
#' @param glob Optional glob pattern to select files (e.g. `"data/*.csv"`).
#' Globs use a literal path separator: `*.csv` only matches files in the
#' target directory and will not match `subdir/file.csv`. Use `**/*.csv` to
#' match recursively across subdirectories. Mutually exclusive with `recursive`.
#' @param recursive If `TRUE`, directory inputs include all descendants;
#' if `FALSE` or `NULL` (default), only direct children of the directory
#' are returned. With no explicit `paths` the directory is the working
#' directory. Mutually exclusive with `glob`.
#' @param dry_run If `TRUE`, report what would be retrieved without writing files.
#' @param progress_callback Optional handle to enable progress bar display.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_get`
dvs_get_impl <- function(paths = character(0), glob = NULL, recursive = NULL, dry_run = NULL, progress_callback = NULL) {
  stopifnot(
    "'glob' must be NULL or character" = is.null(glob) || is.character(glob),
    "'glob' must be NULL or have length 1" = is.null(glob) || length(glob) == 1L,
    "'recursive' must be NULL or logical" = is.null(recursive) || is.logical(recursive),
    "'recursive' must be NULL or have length 1" = is.null(recursive) || length(recursive) == 1L,
    "'dry_run' must be NULL or logical" = is.null(dry_run) || is.logical(dry_run),
    "'dry_run' must be NULL or have length 1" = is.null(dry_run) || length(dry_run) == 1L
  )
  .val <- .Call(C_dvs_get, .call = match.call(), paths, glob, recursive, dry_run, progress_callback)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `dvs_init` (lib.rs:157:15)
#' @title Initialize a DVS repository in the given directory
#' @description Creates the `.dvs` metadata folder and configures storage for versioned files.
#' @param storage_path Path to the storage directory where file contents are kept.
#' @param root_dir Repository root directory. Defaults to the current working directory.
#' @param group Unix group name to set on stored files for shared access.
#' @param metadata_folder_name Name of the metadata folder. Defaults to `.dvs`.
#' @param compression Compression method for stored files. One of `"zstd"`
#' (default) or `"none"`.
#' @return A single-row data frame describing the resulting configuration:
#' `compression`, `metadata_folder_name`, `backend_path`, `backend_group`.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_init`
dvs_init_impl <- function(storage_path, root_dir = NULL, group = NULL, metadata_folder_name = NULL, compression = c("zstd", "none")) {
  stopifnot(
    "'storage_path' must be character" = is.character(storage_path),
    "'storage_path' must have length 1" = length(storage_path) == 1L,
    "'root_dir' must be NULL or character" = is.null(root_dir) || is.character(root_dir),
    "'root_dir' must be NULL or have length 1" = is.null(root_dir) || length(root_dir) == 1L,
    "'group' must be NULL or character" = is.null(group) || is.character(group),
    "'group' must be NULL or have length 1" = is.null(group) || length(group) == 1L,
    "'metadata_folder_name' must be NULL or character" = is.null(metadata_folder_name) || is.character(metadata_folder_name),
    "'metadata_folder_name' must be NULL or have length 1" = is.null(metadata_folder_name) || length(metadata_folder_name) == 1L
  )
  compression <- if (is.factor(compression)) as.character(compression) else compression
  compression <- base::match.arg(compression)
  .val <- .Call(C_dvs_init, .call = match.call(), storage_path, root_dir, group, metadata_folder_name, compression)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `dvs_status` (lib.rs:288:15)
#' @title Report the sync status of DVS-managed files
#' @description Reports the sync status of DVS-managed files. By default all statuses are shown; pass a character vector of status names (e.g. `c("current", "absent")`) to restrict output.
#' @param paths Character vector of file or directory paths to check status for.
#' @param recursive If `TRUE`, directory inputs include all descendants;
#' if `FALSE` or `NULL` (default), only direct children of the directory
#' are returned. The flag only constrains descendants of paths passed
#' explicitly — when `paths` is empty, every tracked file is returned
#' regardless of nesting depth, and `recursive` has no effect.
#' @param glob Optional glob pattern to select files (e.g. `"data/*.csv"`).
#' Globs use a literal path separator: `*.csv` only matches files in the
#' target directory and will not match `subdir/file.csv`. Use `**/*.csv` to
#' match recursively across subdirectories. Mutually exclusive with `recursive`.
#' @param status Character vector of statuses to include. Valid values are
#' `"current"`, `"absent"`, and `"unsynced"`. When empty (default), all
#' statuses are shown.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_status`
dvs_status_impl <- function(paths = character(0), recursive = NULL, glob = NULL, status = c("current", "absent", "unsynced")) {
  stopifnot(
    "'recursive' must be NULL or logical" = is.null(recursive) || is.logical(recursive),
    "'recursive' must be NULL or have length 1" = is.null(recursive) || length(recursive) == 1L,
    "'glob' must be NULL or character" = is.null(glob) || is.character(glob),
    "'glob' must be NULL or have length 1" = is.null(glob) || length(glob) == 1L
  )
  status <- if (is.factor(status)) as.character(status) else status
  status <- base::match.arg(status, several.ok = TRUE)
  .val <- .Call(C_dvs_status, .call = match.call(), paths, recursive, glob, status)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `dvs_version` (lib.rs:513:8)
#' @title Version of the bundled DVS Rust core crate
#' @return The version of the `dvs` Rust crate compiled into this package, as a
#' string (e.g. `"0.3.0"`).
#' @source Generated by miniextendr from Rust fn `dvs_version`
#' @export
dvs_version <- function() {
  .val <- .Call(C_dvs_version, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `dvs_set_threads` (lib.rs:496:15)
#' @title Set the number of threads used by DVS parallel operations
#' @description Controls the thread pool size for add, get, and status operations. Pass `NULL` to revert to automatic detection.
#' @param threads Integer number of threads, or `NULL` to reset.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_set_threads`
dvs_set_threads_impl <- function(threads = NULL) {
  stopifnot(
    "'threads' must be NULL or numeric, logical, or raw" = is.null(threads) || is.numeric(threads) || is.logical(threads) || is.raw(threads),
    "'threads' must be NULL or have length 1" = is.null(threads) || length(threads) == 1L,
    "'threads' must be NULL or non-negative" = is.null(threads) || is.raw(threads) || threads >= 0
  )
  .val <- .Call(C_dvs_set_threads, .call = match.call(), threads)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `format_byte_size` (lib.rs:504:8)
#' @title Format a byte count as a human-readable size string
#' @param size_bytes non-negative integer representing file sizes in bytes.
#' @source Generated by miniextendr from Rust fn `format_byte_size`
#' @export
format_byte_size <- function(size_bytes) {
  stopifnot(
    "'size_bytes' must be numeric, logical, or raw" = is.numeric(size_bytes) || is.logical(size_bytes) || is.raw(size_bytes),
    "'size_bytes' must have length 1" = length(size_bytes) == 1L,
    "'size_bytes' must be non-negative" = is.raw(size_bytes) || size_bytes >= 0
  )
  .val <- .Call(C_format_byte_size, .call = match.call(), size_bytes)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `set_dvs_log_level` (lib.rs:542:8)
#' @title Set the log level for DVS internals
#' @description Controls which log messages from the DVS internals are routed to R's console. `error` and `warn` go to [stderr()]; `info`, `debug`, and `trace` go to stdout.
#' @details The R package does not consult the `RUST_LOG` environment variable. `RUST_LOG=dvs=<level>` only affects the `dvs` CLI binary; in R you must call `set_dvs_log_level()`.
#' 
#' Default at package load: `"off"` — no log output is produced until this function is called.
#' @param level Character string giving the desired log level. The default
#' is `"off"`.
#' @return Called for its side effect; returns `NULL` invisibly.
#' @examples
#' \dontrun{
#' set_dvs_log_level("info")    # opt in
#' set_dvs_log_level("debug")
#' set_dvs_log_level("off")     # restore default (silent)
#' }
#' @source Generated by miniextendr from Rust fn `set_dvs_log_level`
#' @export
set_dvs_log_level <- function(level = c("off", "error", "warn", "info", "debug", "trace")) {
  level <- if (is.factor(level)) as.character(level) else level
  level <- base::match.arg(level)
  .val <- .Call(C_set_dvs_log_level, .call = match.call(), level)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# nocov end
# nolint end
