use anyhow::bail;
use fs_err as fs;
use serde::{Deserialize, Serialize};
use std::io::Read;
use std::path::PathBuf;
use std::sync::OnceLock;
use tempfile::NamedTempFile;
use url::Url;

use crate::audit::AuditEntry;
use crate::auth::get_token;
use crate::utils::http_agent;
use crate::{Backend, Compression, Hashes, RetrieveRequest, StoreRequest};

/// Wraps a reader and reports bytes as they're read, driving the `on_bytes`
/// progress callback. Used to stream an upload body while updating a progress bar.
struct CountingReader<'a, R> {
    inner: R,
    on_bytes: Option<&'a (dyn Fn(u64) + Send + Sync)>,
}

impl<'a, R> CountingReader<'a, R> {
    fn new(inner: R, on_bytes: Option<&'a (dyn Fn(u64) + Send + Sync)>) -> Self {
        Self { inner, on_bytes }
    }
}

impl<R: Read> Read for CountingReader<'_, R> {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        let n = self.inner.read(buf)?;
        if n > 0 {
            if let Some(cb) = self.on_bytes {
                cb(n as u64);
            }
        }
        Ok(n)
    }
}

#[derive(Serialize, Deserialize)]
pub struct InitPayload {
    pub name: String,
    pub group: String,
    pub compression: Compression,
}

#[derive(Serialize, Deserialize)]
pub struct UploadMeta {
    /// Generated by the client once per batch so all files pushed together can be tied back
    pub batch_id: uuid::Uuid,
    pub path: String,
    pub uncompressed_size: i64,
    pub message: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct HistoryPayload {
    #[serde(default)]
    pub paths: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ServerBackend {
    pub name: String,
    pub group: String,
    pub url: Url,
    #[serde(skip)]
    access_token: OnceLock<Option<String>>,
}

impl ServerBackend {
    pub fn new(name: String, group: String, url: Url) -> Self {
        Self {
            name,
            group,
            url,
            access_token: OnceLock::new(),
        }
    }

    fn init_url(&self) -> Url {
        self.url.join("/api/init").unwrap()
    }

    fn blob_url(&self, hash: &str) -> Url {
        self.url
            .join(&format!("api/{}/blobs/{hash}", self.name,))
            .unwrap()
    }

    fn access_url(&self) -> Url {
        self.url
            .join(&format!("/api/{}/access", self.name))
            .unwrap()
    }

    fn history_url(&self) -> Url {
        self.url
            .join(&format!("/api/{}/history", self.name))
            .unwrap()
    }

    fn bearer(&self) -> anyhow::Result<String> {
        let token = self.access_token.get_or_init(|| {
            get_token(&self.url).unwrap_or_else(|e| {
                log::warn!("Could not read the credentials store: {e}");
                None
            })
        });
        match token {
            Some(token) => Ok(format!("Bearer {token}")),
            None => {
                bail!("Could not find access token. Log in first")
            }
        }
    }
}

impl Backend for ServerBackend {
    fn init(&self, compression: Compression) -> anyhow::Result<bool> {
        let url = self.init_url();
        let payload = InitPayload {
            name: self.name.clone(),
            group: self.group.clone(),
            compression,
        };
        let mut resp = http_agent()
            .post(url.as_str())
            .header("authorization", self.bearer()?)
            .send_json(&payload)?;
        match resp.status().as_u16() {
            201 => Ok(false), // created
            200 => Ok(true),  // already existed (group+compression matched)
            401 => {
                bail!("You need to login first")
            }
            409 => {
                bail!(
                    "Server initialization failed: the project already exists with a different group or compression"
                )
            }
            code => bail!(
                "server init failed ({code}): {}",
                resp.body_mut().read_to_string().unwrap_or_default()
            ),
        }
    }

    fn check_access(&self) -> anyhow::Result<()> {
        let mut resp = http_agent()
            .get(self.access_url().as_str())
            .header("authorization", self.bearer()?)
            .call()?;

        match resp.status().as_u16() {
            200 => Ok(()),
            401 => {
                bail!("You need to login first")
            }
            403 => bail!(
                "You are not allowed to access this project, make sure you are logged in with the right user."
            ),
            404 => bail!("The project {} does not exist on the server", self.name),
            code => bail!(
                "access check failed ({code}): {}",
                resp.body_mut().read_to_string().unwrap_or_default()
            ),
        }
    }

    fn store(&self, req: StoreRequest<'_>) -> anyhow::Result<u64> {
        let tmp = NamedTempFile::new()?.into_temp_path();
        req.compression.compress(req.source, &tmp, None)?;
        let stored_size = fs::metadata(&tmp)?.len();
        let upload_meta = serde_json::to_string(&UploadMeta {
            batch_id: req.operation_id,
            path: req.path.to_string_lossy().into(),
            uncompressed_size: req.size as i64,
            message: req.message.map(|s| s.to_string()),
        })?;
        let mut file = CountingReader::new(fs::File::open(&tmp)?, req.on_bytes);
        let form = ureq::unversioned::multipart::Form::new()
            .text("meta", &upload_meta)
            .part(
                "file",
                ureq::unversioned::multipart::Part::reader(&mut file)
                    .file_name("blob")
                    .mime_str("application/octet-stream")?,
            );

        let url = self.blob_url(req.hashes.get_blake3());
        let mut resp = http_agent()
            .put(url.as_str())
            .header("authorization", self.bearer()?)
            .send(form)?;

        match resp.status().as_u16() {
            200 | 201 => Ok(stored_size),
            401 => {
                bail!("You need to login first")
            }
            403 => bail!(
                "You are not allowed to access this project, make sure you are logged in with the right user."
            ),
            code => bail!(
                "upload failed ({code}): {}",
                resp.body_mut().read_to_string().unwrap_or_default()
            ),
        }
    }

    fn retrieve(&self, req: RetrieveRequest<'_>) -> anyhow::Result<bool> {
        let mut url = self.blob_url(req.hashes.get_blake3());
        url.query_pairs_mut()
            .append_pair("path", &req.path.to_string_lossy());

        let mut resp = http_agent()
            .get(url.as_str())
            .header("authorization", self.bearer()?)
            .call()?;

        match resp.status().as_u16() {
            200 => {}
            401 => {
                bail!("You need to login first")
            }
            403 => bail!(
                "You are not allowed to access this project, make sure you are logged in with the right user."
            ),
            404 => return Ok(false),
            code => bail!(
                "download failed ({code}): {}",
                resp.body_mut().read_to_string().unwrap_or_default()
            ),
        }

        let tmp = NamedTempFile::new()?.into_temp_path();
        {
            let mut reader = CountingReader::new(resp.body_mut().as_reader(), req.on_bytes);
            let mut out = fs::File::create(&tmp)?;
            std::io::copy(&mut reader, &mut out)?;
        }

        req.compression.decompress(&tmp, req.target, None)?;
        Ok(true)
    }

    fn exists(&self, hashes: &Hashes) -> anyhow::Result<bool> {
        let url = self.blob_url(hashes.get_blake3());

        match http_agent()
            .head(url.as_str())
            .header("authorization", self.bearer()?)
            .call()?
            .status()
            .as_u16()
        {
            200 => Ok(true),
            401 => {
                bail!("You need to login first")
            }
            403 => bail!(
                "You are not allowed to access this project, make sure you are logged in with the right user."
            ),
            404 => Ok(false),
            _ => bail!("Error while trying to see if a file exists"),
        }
    }

    fn remove(&self, _: &Hashes) -> anyhow::Result<()> {
        // We don't rollback with the server
        Ok(())
    }

    fn get_audit_entries(&self, files: &[PathBuf]) -> anyhow::Result<Vec<AuditEntry>> {
        let url = self.history_url();

        let payload = HistoryPayload {
            paths: files.iter().map(|f| f.to_string_lossy().into()).collect(),
        };

        let mut resp = http_agent()
            .post(url.as_str())
            .header("authorization", self.bearer()?)
            .send_json(&payload)?;

        match resp.status().as_u16() {
            200 => Ok(resp.body_mut().read_json::<Vec<AuditEntry>>()?),
            401 => {
                bail!("You need to login first")
            }
            403 => bail!(
                "You are not allowed to access this project, make sure you are logged in with the right user."
            ),
            code => bail!(
                "history failed ({code}): {}",
                resp.body_mut().read_to_string().unwrap_or_default()
            ),
        }
    }
}
