# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: rebuild the package.
# nolint start
# nocov start

#' @title Hello DVS
#' @description A simple test function to verify the Rust bindings work.
#' @param name A character string with the user's name.
#' @return A greeting string.
#' @examples
#' dvs_hello("World")
#' @export
#' @source Generated by miniextendr from Rust fn `dvs_hello`
dvs_hello <- function(name) {
    .Call(C_dvs_hello, .call = match.call(), name)
}

#' @title DVS Version
#' @description Returns the version of the dvsR Rust backend.
#' @return A character string with the version.
#' @examples
#' dvs_version()
#' @export
#' @source Generated by miniextendr from Rust fn `dvs_version`
dvs_version <- function() {
    .Call(C_dvs_version, .call = match.call())
}

# nocov end
# nolint end
