# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: rebuild the package.
# nolint start
# nocov start

#' @title Hello DVS
#' @description A simple test function to verify the Rust bindings work.
#' @param name A character string with the user's name.
#' @return A greeting string.
#' @examples
#' dvs_hello("World")
#' @export
#' @source Generated by miniextendr from Rust fn `dvs_hello`
dvs_hello <- function(name) {
    .Call(C_dvs_hello, .call = match.call(), name)
}

#' @title DVS Version
#' @description Returns the version of the DVS Rust backend.
#' @return A character string with the version.
#' @examples
#' dvs_version()
#' @export
#' @source Generated by miniextendr from Rust fn `dvs_version`
dvs_version <- function() {
    .Call(C_dvs_version, .call = match.call())
}

#' @title Initialize DVS (internal)
#' @description Internal function returning JSON. Use dvs_init() wrapper.
#' @param storage_dir Character string specifying the path to the storage directory.
#' @param permissions Optional integer specifying file permissions (octal, e.g., 420 for 0644).
#' @param group Optional character string specifying the Unix group for stored files.
#' @return A JSON string with initialization details.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_init_json`
#' @export
dvs_init_json <- function(storage_dir, permissions, group) {
    .Call(C_dvs_init_json, .call = match.call(), storage_dir, permissions, group)
}

#' @title Add Files to DVS (internal)
#' @description Internal function returning JSON. Use dvs_add() wrapper.
#' @param files Character vector of file paths or glob patterns to add.
#' @param message Optional character string describing this version.
#' @return A JSON array of results.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_add_json`
#' @export
dvs_add_json <- function(files, message) {
    .Call(C_dvs_add_json, .call = match.call(), files, message)
}

#' @title Get Files from DVS Storage (internal)
#' @description Internal function returning JSON. Use dvs_get() wrapper.
#' @param files Character vector of file paths or glob patterns to retrieve.
#' @return A JSON array of results.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_get_json`
#' @export
dvs_get_json <- function(files) {
    .Call(C_dvs_get_json, .call = match.call(), files)
}

#' @title Check DVS File Status (internal)
#' @description Internal function returning JSON. Use dvs_status() wrapper.
#' @param files Character vector of file paths or glob patterns to check.
#' @return A JSON array of results.
#' @keywords internal
#' @source Generated by miniextendr from Rust fn `dvs_status_json`
#' @export
dvs_status_json <- function(files) {
    .Call(C_dvs_status_json, .call = match.call(), files)
}

# nocov end
# nolint end
